feat: tmux shortcuts and appropriate aliases

diff --git a/home/zshrc b/home/zshrc
--- a/home/zshrc
+++ b/home/zshrc
@@ -175,9 +175,6 @@ function smallest {
 # ========================================================= #
 # |    Piping Aliases                                     | #
 # ========================================================= #
-alias alertMe='notify-send --urgency=low -i "([?=0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
-
-alias -g alert='| alertMe'
 alias -g gr='| grep -i --color=auto'
 alias -g h='| head'
 alias -g hn='| head -n'
@@ -259,8 +256,65 @@ function HELPER_tmux_launcher() {
 
   tmux switch-client -t $session || tmux attach -t $session
 }
-alias ssh="ssh -t -- /bin/sh -c 'tmux has-session && exec tmux attach || exec tmux' | alertMe"
 alias t="HELPER_tmux_launcher"
+
+function HELPER_tmux_gh_edit_session() {
+  code_loc=$(ghq root)
+  exa --tree --level=2 --recurse --only-dirs $code_loc
+  echo ""
+  echo "Choose a project to open"
+  read project_input
+  num_projects=$(ghq list | grep -i $project_input | wc -l | sed -e 's/^[ \t]*//')
+
+  while [[ ! $num_projects == 1 ]] ; do
+    if [[ $num_projects -gt 1 ]] ; then
+      echo "Invalid input - '$project_input' was ambiguous. Please specify more of the path"
+    else
+      echo "Invalid input - '$project_input' was not found. Please enter a valid project"
+    fi
+    read project_input
+    num_projects=$(ghq list | grep -i $project_input | wc -l | sed -e 's/^[ \t]*//')
+  fi
+
+  project=$(ghq list | grep -i $project_input)
+  project_path="$code_loc/$project"
+  tmux has-session -t $project 2>/dev/null
+  if [[ $? != 0 ]] ; then
+    echo "Tmux has existing session: $project. Attatching to session"
+    tmux switch-client -t $project || tmux attach -t $session
+  else
+    tmux new -s $session -d
+    tmux split-window -v
+    tmux send -t $session "cd $project_path" Enter
+    tmux resize-pane -D 15
+    tmux select-pane -U
+    tmux send -t $session "cd $project_path && vim ." Enter
+    tmux attach
+  fi
+}
+alias te="HELPER_tmux_gh_edit_session"
+
+function HELPER_tmux_gtop() {
+  session="gtop"
+  tmux has-session -t $session 2>/dev/null
+  if [[ $? == 0 ]] ; then
+    tmux new -s $session -d
+    tmxu send -t $session "gtop" Enter
+  fi
+  tmux switch-client -t $session || tmux attach -t $session
+}
+alias tp="HELPER_tmux_gtop"
+
+function HELPER_tmux_ssh() {
+  echo "Enter a enter your ssh host (and flags!)"
+  read cmd
+  cmd=$(echo "$cmd" | sed -e 's/\s*ssh//g' | sed -e 's/^[ \t]*//')
+  ts=$(isoTimestamp)
+  tmux new-session -s "ssh $cmd ($ts)"-d
+  tmux send -t "ssh $cmd" Enter
+  tmux switch-client -t $ || tmux attach -t $host
+}
+alias ts="HELPER_tmux_ssh"
 
 # Call this script and pass a text file with a list of servers. You will ssh to the servers as the current user.
 # Once connected use Ctrl + a to enter commands
